[build]
  command = "npm ci --legacy-peer-deps && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  VITE_API_URL = "https://osbackend-zl1h.onrender.com/task"
  VITE_OPENROUTER_API_KEY = "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"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
