[build]
  command = "npm ci --legacy-peer-deps && npm run build"
  publish = "dist"
  
# Force rebuild with correct API key

[build.environment]
  NODE_VERSION = "18"
  VITE_API_URL = "https://osbackend-zl1h.onrender.com/task"
  VITE_OPENROUTER_API_KEY = "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"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
